### ISSUE TITLE
host meta key is set to the heavy forwarder (TA-Cb_Defense)

### ISSUE THREAD

**Issue by f8al** [carbonblack/cb-defense-splunk-app#1]
If you use this app in its stock form, because of how heavy forwarders and modular inputs work, it skips some queues, and as a result, all of your events come in with the host value set to that of wherever the inputs app is installed.  will submit pull with fix to use host value from deviceInfo.deviceName

**Comment by zacharyestep** [comment]
Trying to take this PR today for the next Splunk app update. Thanks so much!

**Comment by f8al** [comment]
Awesome!  You guys are welcome.  Thanks for being so responsive :)
    	
    	

    	Get Outlook for iOS
    
  




On Tue, Sep 4, 2018 at 12:14 PM -0500, "Zachary Estep" <notifications@github.com> wrote:












Trying to take this PR today for the next Splunk app update. Thanks so much!
