### ISSUE TITLE
CB Defense Add-on Not Loading in Splunk 6.5.4

### ISSUE THREAD

**Issue by ryanwoconnor** [carbonblack/cb-defense-splunk-app#1]
Hi Jason,

I've attempted to install version 1.0.2 of this add-on on Splunk 6.5.4 and when I click on the add-on logo, the inputs screen never loads. The top of the Browser window just says "Loading...". 

Thanks,
Ryan

**Comment by jgarman** [comment]
Does this happen with the released version on splunkbase? Last time we had this report, a customer encountered invalid data in their backend splunk credential store.

**Comment by ryanwoconnor** [comment]
Hi Jason,

I'd need to setup a dev environment to test that version out and see what happens. Unfortunately though we have a requirement of proxy support so that's why we were trying out the commit here that added proxy support. 

Can you tell me more about the invalid data? Was it data for the Add-on? Was it proxy related configs? Is there any kind of error checking that can be done? Just trying to pinpoint what might be broken here.

Thanks,
Ryan

**Comment by jgarman** [comment]
It was some sort of password saved in the credential store - I just looked up the case from the earlier customer and here are the diagnosis steps I received from Splunk support:

Run the following search in the Splunk console as a Splunk admin: `| rest /services/storage/passwords`

Does the above ^^ search return any errors or complete successfully?

**Comment by ryanwoconnor** [comment]
Hi Jason,

It actually does complete successfully. Currently I don't even have any
passwords or settings configured but I'm not seeing anything in the GUI,
the page just doesn't load.

Thanks,
Ryan

Ryan O'Connor

**Comment by jgarman** [comment]
Odd... can you turn on Chrome debugging tools, view the networking tab and monitor for non-200 responses when the "loading" page is spinning away? I'm curious where it's hanging up. The last time this happened was on that password storage REST API route.

**Comment by ryanwoconnor** [comment]
Certainly! Great idea. I just ran it and I got a 404 looking for two files:
common.js and inputs_page.js. That might explain what is going on. Prior to
installing this, we did confirm the SHA256 value for the file from github,
so I know we grabbed the correct one. Any idea if these files were missing
in a specific commit?

Thanks,
Ryan

Ryan O'Connor

**Comment by jgarman** [comment]
Yipes, sorry about that. It appears that those files were 'ignored' via the .gitignore file - they're inside a "build" directory. Ugh. I've fixed the gitignore and pushed the files. Hope this fixes your issue.

**Comment by ryanwoconnor** [comment]
No worries Jason, glad we narrowed this down. I'll get confirmation this
version is OK to install from my customer and report back my findings.
Please wait to close out the issue until I confirm it is working.


Ryan O'Connor

**Comment by jgarman** [comment]
👍 will do. Please let us know if this works.

**Comment by ryanwoconnor** [comment]
Hi Jason,

The GUI loads now, but I don't see any place in the GUI to plugin a proxy URL, etc.

Do you know if this is going to be added in at some point?

Thank you,
Ryan

**Comment by jgarman** [comment]
Just merged in a change to enable this menu in the setup page. Hopefully the (third?) time is the charm- let us know.

**Comment by ryanwoconnor** [comment]
Thanks Jason! So far the app is looking better, I see the correct setup sections now. I'm just waiting on gathering up all required configuration items from the customer and I'll let you know if this new and improved version works!

**Comment by ryanwoconnor** [comment]
We are now successfully pulling data from CB Defense. Thank you to Jason and the Carbonblack team!

**Comment by jgarman** [comment]
You're welcome- thanks for your patience!

**Comment by jgarman** [comment]
BTW the new version of the app (1.0.2) with proxy support is now in queue for approval at Splunkbase

**Comment by ryanwoconnor** [comment]
Awesome! Glad I could thoroughly test the shiny new version for you ;)
